source "https://rubygems.org"

gem "functions_framework", "~> 1.0"
gem "kubeclient"
gem "googleauth"
gem "google-cloud-pubsub"
gem "websocket-client-simple", git: "https://github.com/DerekStride/websocket-client-simple.git"
gem "pry-byebug"
