source "https://rubygems.org"

gem "functions_framework", "~> 1.0"
gem "kubeclient"
gem "googleauth"
gem "google-cloud-pubsub"
gem "websocket-client-simple", path: "/Users/derek/src/github.com/derekstride/websocket-client-simple"
gem "pry-byebug"
