---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio-saves
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  gcePersistentDisk:
    fsType: ext4
    pdName: 
      factorio-saves-pd
