---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-saves-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
