---
    apiVersion: v1
    kind: Service
    metadata:
      name: web
      labels:
        name: web
        app: "factorio-server"
        env: "production"
    spec:
      type: LoadBalancer
      ports:
      - port: 34197
        name: udp
        protocol: UDP
      selector:
        name: web
        app: "factorio-server"
        env: "production"
