---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-saves-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
