---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mc-lutova-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: premium-rwo
  volumeMode: Filesystem
  gcePersistentDisk:
    fsType: ext4
    pdName:
      mc-lutova-data
