---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mc-lutova-0
  labels:
    app: mc-lutova
spec:
  volumeName: pv-mc-lutova-data
  resources:
    requests:
      storage: 25Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: premium-rwo
  volumeMode: Filesystem
