---
apiVersion: v1
kind: Service
metadata:  
  name: web
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  selector:
    app: mc-lutova
  type: LoadBalancer
  loadBalancerIP: 34.130.219.116
  ports:
  - name: tcp
    port: 8379
    targetPort: 25565
    protocol: TCP
