---
apiVersion: v1
kind: Service
metadata:  
  name: web
  annotations:
    networking.gke.io/load-balancer-type: "External"
    cloud.google.com/network-tier: "Standard"
spec:
  selector:
    app: mc-lutova
  type: LoadBalancer
  loadBalancerIP: 35.215.50.255
  ports:
  - name: tcp
    port: 8379
    targetPort: 25565
    protocol: TCP
