---
apiVersion: v1
kind: Service
metadata:  
  name: web-ephemeral
  annotations:
    networking.gke.io/load-balancer-type: "External"
    cloud.google.com/network-tier: "Standard"
spec:
  selector:
    app: mc-lutova
  type: LoadBalancer
  ports:
  - name: tcp
    port: 8379
    targetPort: 25565
    protocol: TCP
