---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mc-lutova
  name: mc-lutova
spec:
  replicas: 1
  serviceName: mc-lutova
  selector:
    matchLabels:
      app: mc-lutova
  template:
    metadata:
      labels:
        app: mc-lutova
    spec:
      containers:
        - name: mc
          image: itzg/minecraft-server
          env:
            - name: EULA
              value: "TRUE"
            - name: VERSION
              value: "1.9.1"
            - name: SERVER_NAME
              value: "Lutova"
            - name: DIFFICULTY
              value: "normal"
            - name: OPS
              value: "ugerest"
            - name: MAX_WORLD_SIZE
              value: "10000"
            - name: SNOOPER_ENABLED
              value: "false"
            - name: SPAWN_PROTECTION
              value: "50"
            - name: TYPE
              value: "FABRIC"
            - name: MODRINTH_PROJECTS
              value: "lithium,phosphor,chunky,fabric-api,cloth-config"
            - name: MODS_FILE
              value: "extras/mods.txt"
            - name: DATAPACKS_FILE
              value: "extras/datapacks.txt"
            - name: MAX_MEMORY
              value: "5G"
            - name: SYNC_SKIP_NEWER_IN_DESTINATION
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: data
        - name: backup
          image: mc-backup
          imagePullPolicy: Never
          securityContext:
            runAsUser: 1000
          env:
            - name: BACKUP_INTERVAL
              value: "6h"
            - name: INITIAL_DELAY
              value: "300"
            - name: PRUNE_BACKUPS_DAYS
              value: "7"
          volumeMounts:
            - mountPath: /data
              name: data
              readOnly: true
            - mountPath: /backups
              name: backups
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: backups
          persistentVolumeClaim:
            claimName: backups
  volumeClaimTemplates:
    - metadata:
      name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
      name: backups
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
