---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mc-lutova
  name: mc-lutova
spec:
  replicas: 1
  serviceName: mc-lutova
  selector:
    matchLabels:
      app: mc-lutova
  template:
    metadata:
      labels:
        app: mc-lutova
    spec:
      containers:
        - name: mc
          image: gcr.io/stride-link/lutova:latest
          resources:
            requests:
              cpu: 1250m
              memory: 12Gi
            limits:
              cpu: 2
              memory: 12Gi
          ports:
            - containerPort: 25565
              protocol: TCP
              name: mc-port
          livenessProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 180
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: MAX_MEMORY
              value: "10G"
          volumeMounts:
            - mountPath: /data
              name: data
        - name: backup
          image: gcr.io/stride-link/mc-backup:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          env:
            - name: BACKUP_INTERVAL
              value: "8h"
            - name: INITIAL_DELAY
              value: "300"
            - name: PRUNE_BACKUPS_DAYS
              value: "3"
          volumeMounts:
            - mountPath: /data
              name: data
              readOnly: true
            - mountPath: /backups
              name: backups
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: backups
          persistentVolumeClaim:
            claimName: backups
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: premium-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
    - metadata:
        name: backups
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
