---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mc-lutova
  name: mc-lutova
spec:
  replicas: 1
  serviceName: mc-lutova
  selector:
    matchLabels:
      app: mc-lutova
  template:
    metadata:
      labels:
        app: mc-lutova
    spec:
      containers:
        - name: mc
          image: gcr.io/stride-link/lutova:latest
          resources:
            requests:
              cpu: 1
              memory: 12Gi
            limits:
              cpu: 1500m
              memory: 12Gi
          ports:
            - containerPort: 25565
              protocol: TCP
              name: mc-port
          livenessProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 180
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: MAX_MEMORY
              value: "10G"
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: premium-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
