---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-saves
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  gcePersistentDisk:
    fsType: ext4
    pdName: 
      mincraft-pd
